services:
  - type: web
    name: time-series-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server --config=gunicorn_config.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
