services:
  - type: web
    name: time-series-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server --config gunicorn_config.py"
